// Auto-generated by OpenLane
module ahb_apb_bridge_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input HCLK,
  input HRESETn,
  input[31:0] HADDR,
  input[31:0] HWDATA,
  input HWRITE,
  input[1:0] HTRANS,
  input HREADY,
  output[31:0] HRDATA,
  output HREADYOUT,
  output HRESP,
  output[31:0] PADDR,
  output[31:0] PWDATA,
  output PWRITE,
  output[3:0] PSEL,
  output PENABLE,
  input[31:0] PRDATA,
  input PREADY,
  input PSLVERR
);
endmodule
