/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\apb_master_if" *)
(* src = "rtl/apb_master_if.sv:1.1-28.10" *)
module \$paramod$6b0e2511c0373e2c7a13b2598d59ab4586bb8acb\apb_master_if (addr_reg, wdata_reg, write_reg, PSEL_in, PENABLE_in, PADDR, PWDATA, PWRITE, PSEL, PENABLE);
  (* src = "rtl/apb_master_if.sv:13.35-13.40" *)
  output [31:0] PADDR;
  wire [31:0] PADDR;
  (* src = "rtl/apb_master_if.sv:17.35-17.42" *)
  output PENABLE;
  wire PENABLE;
  (* src = "rtl/apb_master_if.sv:11.35-11.45" *)
  input PENABLE_in;
  wire PENABLE_in;
  (* src = "rtl/apb_master_if.sv:16.35-16.39" *)
  output [3:0] PSEL;
  wire [3:0] PSEL;
  (* src = "rtl/apb_master_if.sv:10.35-10.42" *)
  input [3:0] PSEL_in;
  wire [3:0] PSEL_in;
  (* src = "rtl/apb_master_if.sv:14.35-14.41" *)
  output [31:0] PWDATA;
  wire [31:0] PWDATA;
  (* src = "rtl/apb_master_if.sv:15.35-15.41" *)
  output PWRITE;
  wire PWRITE;
  (* src = "rtl/apb_master_if.sv:6.35-6.43" *)
  input [31:0] addr_reg;
  wire [31:0] addr_reg;
  (* src = "rtl/apb_master_if.sv:7.35-7.44" *)
  input [31:0] wdata_reg;
  wire [31:0] wdata_reg;
  (* src = "rtl/apb_master_if.sv:8.35-8.44" *)
  input write_reg;
  wire write_reg;
  assign PADDR = addr_reg;
  assign PENABLE = PENABLE_in;
  assign PSEL = PSEL_in;
  assign PWDATA = wdata_reg;
  assign PWRITE = write_reg;
endmodule

(* dynports =  1  *)
(* hdlname = "\\ahb_slave_if" *)
(* src = "rtl/ahb_slave_if.sv:1.1-37.10" *)
module \$paramod$73a3980ba8a68177b0617f0f620fd34f6ef3e417\ahb_slave_if (HCLK, HRESETn, HADDR, HWDATA, HWRITE, HTRANS, HREADY, addr_reg, wdata_reg, write_reg, valid_transfer);
  (* src = "rtl/ahb_slave_if.sv:8.35-8.40" *)
  input [31:0] HADDR;
  wire [31:0] HADDR;
  (* src = "rtl/ahb_slave_if.sv:5.35-5.39" *)
  input HCLK;
  wire HCLK;
  (* src = "rtl/ahb_slave_if.sv:12.35-12.41" *)
  input HREADY;
  wire HREADY;
  (* src = "rtl/ahb_slave_if.sv:6.35-6.42" *)
  input HRESETn;
  wire HRESETn;
  (* src = "rtl/ahb_slave_if.sv:11.35-11.41" *)
  input [1:0] HTRANS;
  wire [1:0] HTRANS;
  (* src = "rtl/ahb_slave_if.sv:9.35-9.41" *)
  input [31:0] HWDATA;
  wire [31:0] HWDATA;
  (* src = "rtl/ahb_slave_if.sv:10.35-10.41" *)
  input HWRITE;
  wire HWRITE;
  (* src = "rtl/ahb_slave_if.sv:14.35-14.43" *)
  output [31:0] addr_reg;
  reg [31:0] addr_reg;
  (* src = "rtl/ahb_slave_if.sv:17.35-17.49" *)
  output valid_transfer;
  wire valid_transfer;
  (* src = "rtl/ahb_slave_if.sv:15.35-15.44" *)
  output [31:0] wdata_reg;
  reg [31:0] wdata_reg;
  (* src = "rtl/ahb_slave_if.sv:16.35-16.44" *)
  output write_reg;
  reg write_reg;
  assign valid_transfer = HREADY & HTRANS[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) write_reg <= 1'h0;
    else if (valid_transfer) write_reg <= HWRITE;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[0] <= 1'h0;
    else if (valid_transfer) wdata_reg[0] <= HWDATA[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[1] <= 1'h0;
    else if (valid_transfer) wdata_reg[1] <= HWDATA[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[2] <= 1'h0;
    else if (valid_transfer) wdata_reg[2] <= HWDATA[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[3] <= 1'h0;
    else if (valid_transfer) wdata_reg[3] <= HWDATA[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[4] <= 1'h0;
    else if (valid_transfer) wdata_reg[4] <= HWDATA[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[5] <= 1'h0;
    else if (valid_transfer) wdata_reg[5] <= HWDATA[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[6] <= 1'h0;
    else if (valid_transfer) wdata_reg[6] <= HWDATA[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[7] <= 1'h0;
    else if (valid_transfer) wdata_reg[7] <= HWDATA[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[8] <= 1'h0;
    else if (valid_transfer) wdata_reg[8] <= HWDATA[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[9] <= 1'h0;
    else if (valid_transfer) wdata_reg[9] <= HWDATA[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[10] <= 1'h0;
    else if (valid_transfer) wdata_reg[10] <= HWDATA[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[11] <= 1'h0;
    else if (valid_transfer) wdata_reg[11] <= HWDATA[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[12] <= 1'h0;
    else if (valid_transfer) wdata_reg[12] <= HWDATA[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[13] <= 1'h0;
    else if (valid_transfer) wdata_reg[13] <= HWDATA[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[14] <= 1'h0;
    else if (valid_transfer) wdata_reg[14] <= HWDATA[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[15] <= 1'h0;
    else if (valid_transfer) wdata_reg[15] <= HWDATA[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[16] <= 1'h0;
    else if (valid_transfer) wdata_reg[16] <= HWDATA[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[17] <= 1'h0;
    else if (valid_transfer) wdata_reg[17] <= HWDATA[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[18] <= 1'h0;
    else if (valid_transfer) wdata_reg[18] <= HWDATA[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[19] <= 1'h0;
    else if (valid_transfer) wdata_reg[19] <= HWDATA[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[20] <= 1'h0;
    else if (valid_transfer) wdata_reg[20] <= HWDATA[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[21] <= 1'h0;
    else if (valid_transfer) wdata_reg[21] <= HWDATA[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[22] <= 1'h0;
    else if (valid_transfer) wdata_reg[22] <= HWDATA[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[23] <= 1'h0;
    else if (valid_transfer) wdata_reg[23] <= HWDATA[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[24] <= 1'h0;
    else if (valid_transfer) wdata_reg[24] <= HWDATA[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[25] <= 1'h0;
    else if (valid_transfer) wdata_reg[25] <= HWDATA[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[26] <= 1'h0;
    else if (valid_transfer) wdata_reg[26] <= HWDATA[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[27] <= 1'h0;
    else if (valid_transfer) wdata_reg[27] <= HWDATA[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[28] <= 1'h0;
    else if (valid_transfer) wdata_reg[28] <= HWDATA[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[29] <= 1'h0;
    else if (valid_transfer) wdata_reg[29] <= HWDATA[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[30] <= 1'h0;
    else if (valid_transfer) wdata_reg[30] <= HWDATA[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) wdata_reg[31] <= 1'h0;
    else if (valid_transfer) wdata_reg[31] <= HWDATA[31];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[0] <= 1'h0;
    else if (valid_transfer) addr_reg[0] <= HADDR[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[1] <= 1'h0;
    else if (valid_transfer) addr_reg[1] <= HADDR[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[2] <= 1'h0;
    else if (valid_transfer) addr_reg[2] <= HADDR[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[3] <= 1'h0;
    else if (valid_transfer) addr_reg[3] <= HADDR[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[4] <= 1'h0;
    else if (valid_transfer) addr_reg[4] <= HADDR[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[5] <= 1'h0;
    else if (valid_transfer) addr_reg[5] <= HADDR[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[6] <= 1'h0;
    else if (valid_transfer) addr_reg[6] <= HADDR[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[7] <= 1'h0;
    else if (valid_transfer) addr_reg[7] <= HADDR[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[8] <= 1'h0;
    else if (valid_transfer) addr_reg[8] <= HADDR[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[9] <= 1'h0;
    else if (valid_transfer) addr_reg[9] <= HADDR[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[10] <= 1'h0;
    else if (valid_transfer) addr_reg[10] <= HADDR[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[11] <= 1'h0;
    else if (valid_transfer) addr_reg[11] <= HADDR[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[12] <= 1'h0;
    else if (valid_transfer) addr_reg[12] <= HADDR[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[13] <= 1'h0;
    else if (valid_transfer) addr_reg[13] <= HADDR[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[14] <= 1'h0;
    else if (valid_transfer) addr_reg[14] <= HADDR[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[15] <= 1'h0;
    else if (valid_transfer) addr_reg[15] <= HADDR[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[16] <= 1'h0;
    else if (valid_transfer) addr_reg[16] <= HADDR[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[17] <= 1'h0;
    else if (valid_transfer) addr_reg[17] <= HADDR[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[18] <= 1'h0;
    else if (valid_transfer) addr_reg[18] <= HADDR[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[19] <= 1'h0;
    else if (valid_transfer) addr_reg[19] <= HADDR[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[20] <= 1'h0;
    else if (valid_transfer) addr_reg[20] <= HADDR[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[21] <= 1'h0;
    else if (valid_transfer) addr_reg[21] <= HADDR[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[22] <= 1'h0;
    else if (valid_transfer) addr_reg[22] <= HADDR[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[23] <= 1'h0;
    else if (valid_transfer) addr_reg[23] <= HADDR[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[24] <= 1'h0;
    else if (valid_transfer) addr_reg[24] <= HADDR[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[25] <= 1'h0;
    else if (valid_transfer) addr_reg[25] <= HADDR[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[26] <= 1'h0;
    else if (valid_transfer) addr_reg[26] <= HADDR[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[27] <= 1'h0;
    else if (valid_transfer) addr_reg[27] <= HADDR[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[28] <= 1'h0;
    else if (valid_transfer) addr_reg[28] <= HADDR[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[29] <= 1'h0;
    else if (valid_transfer) addr_reg[29] <= HADDR[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[30] <= 1'h0;
    else if (valid_transfer) addr_reg[30] <= HADDR[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ahb_slave_if.sv:20.1-31.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) addr_reg[31] <= 1'h0;
    else if (valid_transfer) addr_reg[31] <= HADDR[31];
endmodule

(* dynports =  1  *)
(* hdlname = "\\address_decoder" *)
(* src = "rtl/address_decoder.sv:1.1-20.10" *)
module \$paramod$9aa7f8c73f38399d81c9421d1787a3c571c65c83\address_decoder (addr_reg, PSEL);
  (* src = "rtl/address_decoder.sv:6.35-6.39" *)
  output [3:0] PSEL;
  wire [3:0] PSEL;
  (* src = "rtl/address_decoder.sv:5.35-5.43" *)
  input [31:0] addr_reg;
  wire [31:0] addr_reg;
  assign PSEL[0] = ~(addr_reg[13] | addr_reg[12]);
  assign PSEL[1] = addr_reg[12] & ~(addr_reg[13]);
  assign PSEL[2] = addr_reg[13] & ~(addr_reg[12]);
  assign PSEL[3] = addr_reg[13] & addr_reg[12];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/ahb_apb_bridge_top.sv:1.1-102.10" *)
module ahb_apb_bridge_top(HCLK, HRESETn, HADDR, HWDATA, HWRITE, HTRANS, HREADY, HRDATA, HREADYOUT, HRESP, PADDR, PWDATA, PWRITE, PSEL, PENABLE, PRDATA, PREADY, PSLVERR);
  (* src = "rtl/ahb_apb_bridge_top.sv:0.0-0.0" *)
  wire _0_;
  (* src = "rtl/ahb_apb_bridge_top.sv:0.0-0.0" *)
  wire _1_;
  (* src = "rtl/ahb_apb_bridge_top.sv:0.0-0.0" *)
  wire _2_;
  (* src = "rtl/ahb_apb_bridge_top.sv:0.0-0.0" *)
  wire _3_;
  (* src = "rtl/ahb_apb_bridge_top.sv:10.38-10.43" *)
  input [31:0] HADDR;
  wire [31:0] HADDR;
  (* src = "rtl/ahb_apb_bridge_top.sv:6.38-6.42" *)
  input HCLK;
  wire HCLK;
  (* src = "rtl/ahb_apb_bridge_top.sv:16.38-16.44" *)
  output [31:0] HRDATA;
  wire [31:0] HRDATA;
  (* src = "rtl/ahb_apb_bridge_top.sv:14.38-14.44" *)
  input HREADY;
  wire HREADY;
  (* src = "rtl/ahb_apb_bridge_top.sv:17.38-17.47" *)
  output HREADYOUT;
  wire HREADYOUT;
  (* src = "rtl/ahb_apb_bridge_top.sv:7.38-7.45" *)
  input HRESETn;
  wire HRESETn;
  (* src = "rtl/ahb_apb_bridge_top.sv:18.38-18.43" *)
  output HRESP;
  wire HRESP;
  (* src = "rtl/ahb_apb_bridge_top.sv:13.38-13.44" *)
  input [1:0] HTRANS;
  wire [1:0] HTRANS;
  (* src = "rtl/ahb_apb_bridge_top.sv:11.38-11.44" *)
  input [31:0] HWDATA;
  wire [31:0] HWDATA;
  (* src = "rtl/ahb_apb_bridge_top.sv:12.38-12.44" *)
  input HWRITE;
  wire HWRITE;
  (* src = "rtl/ahb_apb_bridge_top.sv:21.38-21.43" *)
  output [31:0] PADDR;
  wire [31:0] PADDR;
  (* src = "rtl/ahb_apb_bridge_top.sv:25.38-25.45" *)
  output PENABLE;
  wire PENABLE;
  (* src = "rtl/ahb_apb_bridge_top.sv:27.38-27.44" *)
  input [31:0] PRDATA;
  wire [31:0] PRDATA;
  (* src = "rtl/ahb_apb_bridge_top.sv:28.38-28.44" *)
  input PREADY;
  wire PREADY;
  (* src = "rtl/ahb_apb_bridge_top.sv:24.38-24.42" *)
  output [3:0] PSEL;
  wire [3:0] PSEL;
  (* src = "rtl/ahb_apb_bridge_top.sv:29.38-29.45" *)
  input PSLVERR;
  wire PSLVERR;
  (* src = "rtl/ahb_apb_bridge_top.sv:22.38-22.44" *)
  output [31:0] PWDATA;
  wire [31:0] PWDATA;
  (* src = "rtl/ahb_apb_bridge_top.sv:23.38-23.44" *)
  output PWRITE;
  wire PWRITE;
  (* src = "rtl/ahb_apb_bridge_top.sv:32.24-32.32" *)
  wire [31:0] addr_reg;
  (* src = "rtl/ahb_apb_bridge_top.sv:39.24-39.35" *)
  wire fsm_penable;
  (* src = "rtl/ahb_apb_bridge_top.sv:38.24-38.32" *)
  wire fsm_psel;
  (* src = "rtl/ahb_apb_bridge_top.sv:37.24-37.36" *)
  wire [3:0] psel_decoded;
  (* src = "rtl/ahb_apb_bridge_top.sv:35.24-35.38" *)
  wire valid_transfer;
  (* src = "rtl/ahb_apb_bridge_top.sv:33.24-33.33" *)
  wire [31:0] wdata_reg;
  (* src = "rtl/ahb_apb_bridge_top.sv:34.24-34.33" *)
  wire write_reg;
  assign _0_ = psel_decoded[0] & fsm_psel;
  assign _1_ = fsm_psel & psel_decoded[1];
  assign _2_ = fsm_psel & psel_decoded[2];
  assign _3_ = fsm_psel & psel_decoded[3];
  (* src = "rtl/ahb_apb_bridge_top.sv:45.3-57.2" *)
  \$paramod$73a3980ba8a68177b0617f0f620fd34f6ef3e417\ahb_slave_if  u_ahb_slave_if (
    .HADDR(HADDR),
    .HCLK(HCLK),
    .HREADY(HREADY),
    .HRESETn(HRESETn),
    .HTRANS(HTRANS),
    .HWDATA(HWDATA),
    .HWRITE(HWRITE),
    .addr_reg(addr_reg),
    .valid_transfer(valid_transfer),
    .wdata_reg(wdata_reg),
    .write_reg(write_reg)
  );
  (* src = "rtl/ahb_apb_bridge_top.sv:86.3-97.2" *)
  \$paramod$6b0e2511c0373e2c7a13b2598d59ab4586bb8acb\apb_master_if  u_apb_master (
    .PADDR(PADDR),
    .PENABLE(PENABLE),
    .PENABLE_in(fsm_penable),
    .PSEL(PSEL),
    .PSEL_in({ _3_, _2_, _1_, _0_ }),
    .PWDATA(PWDATA),
    .PWRITE(PWRITE),
    .addr_reg(addr_reg),
    .wdata_reg(wdata_reg),
    .write_reg(write_reg)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/ahb_apb_bridge_top.sv:60.12-70.2" *)
  bridge_fsm u_bridge_fsm (
    .HCLK(HCLK),
    .HREADYOUT(HREADYOUT),
    .HRESETn(HRESETn),
    .HRESP(HRESP),
    .PENABLE(fsm_penable),
    .PREADY(PREADY),
    .PSEL(fsm_psel),
    .PSLVERR(PSLVERR),
    .valid_transfer(valid_transfer)
  );
  (* src = "rtl/ahb_apb_bridge_top.sv:76.3-79.2" *)
  \$paramod$9aa7f8c73f38399d81c9421d1787a3c571c65c83\address_decoder  u_decoder (
    .PSEL(psel_decoded),
    .addr_reg(addr_reg)
  );
  assign HRDATA = PRDATA;
endmodule

(* src = "rtl/bridge_fsm.sv:1.1-85.10" *)
module bridge_fsm(HCLK, HRESETn, valid_transfer, PREADY, PSLVERR, PSEL, PENABLE, HREADYOUT, HRESP);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "rtl/bridge_fsm.sv:2.18-2.22" *)
  input HCLK;
  wire HCLK;
  (* src = "rtl/bridge_fsm.sv:10.18-10.27" *)
  output HREADYOUT;
  wire HREADYOUT;
  (* src = "rtl/bridge_fsm.sv:3.18-3.25" *)
  input HRESETn;
  wire HRESETn;
  (* src = "rtl/bridge_fsm.sv:11.18-11.23" *)
  output HRESP;
  wire HRESP;
  (* src = "rtl/bridge_fsm.sv:9.18-9.25" *)
  output PENABLE;
  wire PENABLE;
  (* src = "rtl/bridge_fsm.sv:5.18-5.24" *)
  input PREADY;
  wire PREADY;
  (* src = "rtl/bridge_fsm.sv:8.18-8.22" *)
  output PSEL;
  wire PSEL;
  (* src = "rtl/bridge_fsm.sv:6.18-6.25" *)
  input PSLVERR;
  wire PSLVERR;
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* enum_value_11 = "\\ERROR" *)
  (* src = "rtl/bridge_fsm.sv:21.16-21.26" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] next_state;
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\SETUP" *)
  (* enum_value_10 = "\\ACCESS" *)
  (* enum_value_11 = "\\ERROR" *)
  (* src = "rtl/bridge_fsm.sv:21.9-21.14" *)
  (* wiretype = "\\state_t" *)
  reg [1:0] state;
  (* src = "rtl/bridge_fsm.sv:4.18-4.32" *)
  input valid_transfer;
  wire valid_transfer;
  assign _01_ = ~valid_transfer;
  assign _02_ = state[0] | state[1];
  assign _03_ = valid_transfer | _02_;
  assign PENABLE = state[1] & ~(state[0]);
  assign _04_ = ~(PREADY | PSLVERR);
  assign _05_ = ~(PENABLE & _04_);
  assign _00_ = _03_ & _05_;
  assign HRESP = state[0] & state[1];
  assign PSEL = _02_ & ~(HRESP);
  assign _06_ = ~(PREADY & PENABLE);
  assign HREADYOUT = ~(PSEL & _06_);
  assign _07_ = ~(PSLVERR & PENABLE);
  assign _08_ = _01_ | _02_;
  assign next_state[0] = ~(_07_ & _08_);
  assign next_state[1] = PENABLE ? PSLVERR : PSEL;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/bridge_fsm.sv:24.1-29.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) state[0] <= 1'h0;
    else if (_00_) state[0] <= next_state[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/bridge_fsm.sv:24.1-29.4" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) state[1] <= 1'h0;
    else if (_00_) state[1] <= next_state[1];
endmodule
